version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven..."

  build:
    commands:
      - echo "Building and testing the application..."
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'